FROM alpine:latest

ARG ARG_PB_VERSION=0.22.21
ARG ARG_PB_PORT=8090

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${ARG_PB_VERSION}/pocketbase_${ARG_PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

EXPOSE ${ARG_PB_PORT}
ENV VE_PB_PORT=${ARG_PB_PORT}
CMD /pb/pocketbase serve --http=0.0.0.0:${VE_PB_PORT}
