FROM node:22-bookworm

RUN apt update && apt upgrade -y && \
apt clean && \
rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN npm install -g npm@latest && \
npm install -g pnpm && \
pnpm --version

USER node

# Add github to known hosts
RUN mkdir -p /home/node/.ssh && \
ssh-keyscan github.com >> /home/node/.ssh/known_hosts

# Setup pnpm default store location to sync with the host on the docker compose file.
RUN export SHELL="bash" && pnpm setup
ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"
RUN SHELL="bash" && \
pnpm config set store-dir "${PNPM_HOME}/store" && \
pnpm install -g typescript && \
pnpm -g install pnpm && \
pnpm --version && tsc --version

WORKDIR /home/node/workspace
