log:
  level: WARN 
  filePath: /var/log/traefik/traefik.log
  maxAge: 10
  maxBackups: 20
  compress: true
api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: example.com #TODO: Change this to your domain
            sans: 
              - "*.example.com" #TODO: Change this to your domain
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
certificatesResolvers:
  cloudflare:
    acme:
      email: email@cloudflareaccount.com # TODO: Change this to your email address
      storage: acme.json # NOTE: This file needs to have permissions 600
      # IMPORTANT: Activate the prod environment before going live. Use the staging environment for testing.
      #caServer: https://acme-v02.api.letsencrypt.org/directory
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        #disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
